// This file is auto-generated by @hey-api/openapi-ts

export const ApiKeyResponseSchema = {
    properties: {
        api_key: {
            type: 'string',
            title: 'Api Key'
        }
    },
    type: 'object',
    required: ['api_key'],
    title: 'ApiKeyResponse'
} as const;

export const Body_login_for_access_token_auth_token_postSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login_for_access_token_auth_token_post'
} as const;

export const CreateUserRequestSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        first_name: {
            type: 'string',
            title: 'First Name'
        },
        last_name: {
            type: 'string',
            title: 'Last Name'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        phone_number: {
            type: 'string',
            title: 'Phone Number'
        }
    },
    type: 'object',
    required: ['username', 'email', 'first_name', 'last_name', 'password', 'role', 'phone_number'],
    title: 'CreateUserRequest'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const PaginatedTestResultsSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/TestResultResponse'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        skip: {
            type: 'integer',
            title: 'Skip'
        },
        limit: {
            type: 'integer',
            title: 'Limit'
        }
    },
    type: 'object',
    required: ['items', 'total', 'skip', 'limit'],
    title: 'PaginatedTestResults'
} as const;

export const TestResultRequestSchema = {
    properties: {
        test_date: {
            type: 'string',
            format: 'date',
            title: 'Test Date'
        },
        build: {
            type: 'string',
            minLength: 3,
            title: 'Build'
        },
        overall_test_rate: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 100,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Overall Test Rate'
        },
        superlaser_concentration_static_check: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 100,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Superlaser Concentration Static Check'
        },
        hypermatter_reactor_core_startup_test: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 100,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hypermatter Reactor Core Startup Test'
        },
        sublight_ion_engines_sanity_check: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 100,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sublight Ion Engines Sanity Check'
        },
        superlaser_focal_lenses_coordination_test: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 100,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Superlaser Focal Lenses Coordination Test'
        },
        class_3_hyperdrive_coordinate_input_test: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 100,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Class 3 Hyperdrive Coordinate Input Test'
        },
        deflector_shield_generator_stress_test: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 100,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deflector Shield Generator Stress Test'
        },
        turbolaser_ion_cannon_power_on_test: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 100,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Turbolaser Ion Cannon Power On Test'
        },
        tractor_beam_projectors_response_test: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 100,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tractor Beam Projectors Response Test'
        },
        exhaust_ports_control_test: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 100,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Exhaust Ports Control Test'
        },
        kyber_crystal_sample_response_test: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 100,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Kyber Crystal Sample Response Test'
        }
    },
    type: 'object',
    required: ['test_date', 'build'],
    title: 'TestResultRequest'
} as const;

export const TestResultResponseSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        test_date: {
            type: 'string',
            format: 'date',
            title: 'Test Date'
        },
        build: {
            type: 'string',
            title: 'Build'
        },
        overall_test_rate: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Overall Test Rate'
        },
        superlaser_concentration_static_check: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Superlaser Concentration Static Check'
        },
        hypermatter_reactor_core_startup_test: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hypermatter Reactor Core Startup Test'
        },
        sublight_ion_engines_sanity_check: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sublight Ion Engines Sanity Check'
        },
        superlaser_focal_lenses_coordination_test: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Superlaser Focal Lenses Coordination Test'
        },
        class_3_hyperdrive_coordinate_input_test: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Class 3 Hyperdrive Coordinate Input Test'
        },
        deflector_shield_generator_stress_test: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deflector Shield Generator Stress Test'
        },
        turbolaser_ion_cannon_power_on_test: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Turbolaser Ion Cannon Power On Test'
        },
        tractor_beam_projectors_response_test: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tractor Beam Projectors Response Test'
        },
        exhaust_ports_control_test: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Exhaust Ports Control Test'
        },
        kyber_crystal_sample_response_test: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Kyber Crystal Sample Response Test'
        },
        owner_id: {
            type: 'integer',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['id', 'test_date', 'build', 'overall_test_rate', 'superlaser_concentration_static_check', 'hypermatter_reactor_core_startup_test', 'sublight_ion_engines_sanity_check', 'superlaser_focal_lenses_coordination_test', 'class_3_hyperdrive_coordinate_input_test', 'deflector_shield_generator_stress_test', 'turbolaser_ion_cannon_power_on_test', 'tractor_beam_projectors_response_test', 'exhaust_ports_control_test', 'kyber_crystal_sample_response_test', 'owner_id'],
    title: 'TestResultResponse'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type'
        }
    },
    type: 'object',
    required: ['access_token', 'token_type'],
    title: 'Token'
} as const;

export const UserResponseSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        first_name: {
            type: 'string',
            title: 'First Name'
        },
        last_name: {
            type: 'string',
            title: 'Last Name'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        phone_number: {
            type: 'string',
            title: 'Phone Number'
        }
    },
    type: 'object',
    required: ['id', 'email', 'username', 'first_name', 'last_name', 'is_active', 'role', 'phone_number'],
    title: 'UserResponse'
} as const;

export const UserVerificationSchema = {
    properties: {
        password: {
            type: 'string',
            title: 'Password'
        },
        new_password: {
            type: 'string',
            minLength: 6,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['password', 'new_password'],
    title: 'UserVerification'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;