// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ReadAllAdminTestResultsGetResponse, UpdateTestResultAdminTestResultsTestResultIdPutData, UpdateTestResultAdminTestResultsTestResultIdPutResponse, DeleteTestResultAdminTestResultsTestResultIdDeleteData, DeleteTestResultAdminTestResultsTestResultIdDeleteResponse, CreateUserAdminUserPostData, CreateUserAdminUserPostResponse, CreateUserAuthPostData, CreateUserAuthPostResponse, LoginForAccessTokenAuthTokenPostData, LoginForAccessTokenAuthTokenPostResponse, GenerateApiKeyAuthApiKeyPostResponse, HealthCheckHealthyGetResponse, ReadAllTestResultsGetData, ReadAllTestResultsGetResponse, CreateTestResultTestResultsPostData, CreateTestResultTestResultsPostResponse, QueryTestResultsTestResultsQueryGetData, QueryTestResultsTestResultsQueryGetResponse, ReadTestResultTestResultsTestResultIdGetData, ReadTestResultTestResultsTestResultIdGetResponse, GetUserUserGetResponse, ChangePasswordUserPasswordPutData, ChangePasswordUserPasswordPutResponse, ChangeEmailUserEmailEmailPutData, ChangeEmailUserEmailEmailPutResponse } from './types.gen';

export class AdminService {
    /**
     * Read All
     * @returns TestResultResponse Successful Response
     * @throws ApiError
     */
    public static readAllAdminTestResultsGet(): CancelablePromise<ReadAllAdminTestResultsGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/admin/test-results'
        });
    }
    
    /**
     * Update Test Result
     * @param data The data for the request.
     * @param data.testResultId
     * @param data.requestBody
     * @returns void Successful Response
     * @throws ApiError
     */
    public static updateTestResultAdminTestResultsTestResultIdPut(data: UpdateTestResultAdminTestResultsTestResultIdPutData): CancelablePromise<UpdateTestResultAdminTestResultsTestResultIdPutResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/admin/test-results/{test_result_id}',
            path: {
                test_result_id: data.testResultId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Test Result
     * @param data The data for the request.
     * @param data.testResultId
     * @returns void Successful Response
     * @throws ApiError
     */
    public static deleteTestResultAdminTestResultsTestResultIdDelete(data: DeleteTestResultAdminTestResultsTestResultIdDeleteData): CancelablePromise<DeleteTestResultAdminTestResultsTestResultIdDeleteResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/admin/test-results/{test_result_id}',
            path: {
                test_result_id: data.testResultId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static createUserAdminUserPost(data: CreateUserAdminUserPostData): CancelablePromise<CreateUserAdminUserPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/admin/user',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class AuthService {
    /**
     * Create User
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static createUserAuthPost(data: CreateUserAuthPostData): CancelablePromise<CreateUserAuthPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/auth/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Login For Access Token
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginForAccessTokenAuthTokenPost(data: LoginForAccessTokenAuthTokenPostData): CancelablePromise<LoginForAccessTokenAuthTokenPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/auth/token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Generate Api Key
     * Generate a new long-lived API key for the logged-in user, replacing
     * any previous one. The plaintext key is only ever returned here - only
     * its hash is stored, so save it somewhere safe.
     * @returns ApiKeyResponse Successful Response
     * @throws ApiError
     */
    public static generateApiKeyAuthApiKeyPost(): CancelablePromise<GenerateApiKeyAuthApiKeyPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/auth/api-key'
        });
    }
}

export class DefaultService {
    /**
     * Health Check
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static healthCheckHealthyGet(): CancelablePromise<HealthCheckHealthyGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/healthy'
        });
    }
}

export class TestResultsService {
    /**
     * Read All
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @param data.attribute
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static readAllTestResultsGet(data: ReadAllTestResultsGetData = {}): CancelablePromise<ReadAllTestResultsGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/test-results/',
            query: {
                skip: data.skip,
                limit: data.limit,
                attribute: data.attribute
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Test Result
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static createTestResultTestResultsPost(data: CreateTestResultTestResultsPostData): CancelablePromise<CreateTestResultTestResultsPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/test-results/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Query Test Results
     * @param data The data for the request.
     * @param data.q Boolean filter expression. Fields: build (string) and any numeric column (overall_test_rate or a subsystem test). Operators: = == != < <= > >=. Combine with AND / OR and parentheses. Example: (overall_test_rate < 92) AND (superlaser_concentration_static_check > 95)
     * @param data.skip
     * @param data.limit
     * @returns PaginatedTestResults Successful Response
     * @throws ApiError
     */
    public static queryTestResultsTestResultsQueryGet(data: QueryTestResultsTestResultsQueryGetData): CancelablePromise<QueryTestResultsTestResultsQueryGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/test-results/query',
            query: {
                q: data.q,
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Test Result
     * @param data The data for the request.
     * @param data.testResultId
     * @returns TestResultResponse Successful Response
     * @throws ApiError
     */
    public static readTestResultTestResultsTestResultIdGet(data: ReadTestResultTestResultsTestResultIdGetData): CancelablePromise<ReadTestResultTestResultsTestResultIdGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/test-results/{test_result_id}',
            path: {
                test_result_id: data.testResultId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UserService {
    /**
     * Get User
     * @returns UserResponse Successful Response
     * @throws ApiError
     */
    public static getUserUserGet(): CancelablePromise<GetUserUserGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/user/'
        });
    }
    
    /**
     * Change Password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns void Successful Response
     * @throws ApiError
     */
    public static changePasswordUserPasswordPut(data: ChangePasswordUserPasswordPutData): CancelablePromise<ChangePasswordUserPasswordPutResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/user/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Change Email
     * @param data The data for the request.
     * @param data.email
     * @returns void Successful Response
     * @throws ApiError
     */
    public static changeEmailUserEmailEmailPut(data: ChangeEmailUserEmailEmailPutData): CancelablePromise<ChangeEmailUserEmailEmailPutResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/user/email/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}