// This file is auto-generated by @hey-api/openapi-ts

export type ApiKeyResponse = {
    api_key: string;
};

export type Body_login_for_access_token_auth_token_post = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CreateUserRequest = {
    username: string;
    email: string;
    first_name: string;
    last_name: string;
    password: string;
    role: string;
    phone_number: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type PaginatedTestResults = {
    items: Array<TestResultResponse>;
    total: number;
    skip: number;
    limit: number;
};

export type TestResultRequest = {
    test_date: string;
    build: string;
    superlaser_concentration_static_check?: (number | null);
    hypermatter_reactor_core_startup_test?: (number | null);
    sublight_ion_engines_sanity_check?: (number | null);
    superlaser_focal_lenses_coordination_test?: (number | null);
    class_3_hyperdrive_coordinate_input_test?: (number | null);
    deflector_shield_generator_stress_test?: (number | null);
    turbolaser_ion_cannon_power_on_test?: (number | null);
    tractor_beam_projectors_response_test?: (number | null);
    exhaust_ports_control_test?: (number | null);
    kyber_crystal_sample_response_test?: (number | null);
};

export type TestResultResponse = {
    id: number;
    test_date: string;
    build: string;
    overall_test_rate: (number | null);
    superlaser_concentration_static_check: (number | null);
    hypermatter_reactor_core_startup_test: (number | null);
    sublight_ion_engines_sanity_check: (number | null);
    superlaser_focal_lenses_coordination_test: (number | null);
    class_3_hyperdrive_coordinate_input_test: (number | null);
    deflector_shield_generator_stress_test: (number | null);
    turbolaser_ion_cannon_power_on_test: (number | null);
    tractor_beam_projectors_response_test: (number | null);
    exhaust_ports_control_test: (number | null);
    kyber_crystal_sample_response_test: (number | null);
    owner_id: number;
};

export type Token = {
    access_token: string;
    token_type: string;
};

export type UserResponse = {
    id: number;
    email: string;
    username: string;
    first_name: string;
    last_name: string;
    is_active: boolean;
    role: string;
    phone_number: string;
};

export type UserVerification = {
    password: string;
    new_password: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ReadAllAdminTestResultsGetResponse = (Array<TestResultResponse>);

export type UpdateTestResultAdminTestResultsTestResultIdPutData = {
    requestBody: TestResultRequest;
    testResultId: number;
};

export type UpdateTestResultAdminTestResultsTestResultIdPutResponse = (void);

export type DeleteTestResultAdminTestResultsTestResultIdDeleteData = {
    testResultId: number;
};

export type DeleteTestResultAdminTestResultsTestResultIdDeleteResponse = (void);

export type ReadAllUsersAdminUserGetResponse = (Array<UserResponse>);

export type CreateUserAdminUserPostData = {
    requestBody: CreateUserRequest;
};

export type CreateUserAdminUserPostResponse = (unknown);

export type DeleteUserAdminUserUserIdDeleteData = {
    userId: number;
};

export type DeleteUserAdminUserUserIdDeleteResponse = (void);

export type CreateUserAuthPostData = {
    requestBody: CreateUserRequest;
};

export type CreateUserAuthPostResponse = (unknown);

export type LoginForAccessTokenAuthTokenPostData = {
    formData: Body_login_for_access_token_auth_token_post;
};

export type LoginForAccessTokenAuthTokenPostResponse = (Token);

export type GenerateApiKeyAuthApiKeyPostResponse = (ApiKeyResponse);

export type HealthCheckHealthyGetResponse = (unknown);

export type ReadAllTestResultsGetData = {
    attribute?: ('superlaser_concentration_static_check' | 'hypermatter_reactor_core_startup_test' | 'sublight_ion_engines_sanity_check' | 'superlaser_focal_lenses_coordination_test' | 'class_3_hyperdrive_coordinate_input_test' | 'deflector_shield_generator_stress_test' | 'turbolaser_ion_cannon_power_on_test' | 'tractor_beam_projectors_response_test' | 'exhaust_ports_control_test' | 'kyber_crystal_sample_response_test' | null);
    limit?: number;
    skip?: number;
};

export type ReadAllTestResultsGetResponse = (unknown);

export type CreateTestResultTestResultsPostData = {
    requestBody: TestResultRequest;
};

export type CreateTestResultTestResultsPostResponse = (unknown);

export type QueryTestResultsTestResultsQueryGetData = {
    limit?: number;
    /**
     * Boolean filter expression. Fields: build (string) and any numeric column (overall_test_rate or a subsystem test). Operators: = == != < <= > >=. Combine with AND / OR and parentheses. Example: (overall_test_rate < 92) AND (superlaser_concentration_static_check > 95)
     */
    q: string;
    skip?: number;
};

export type QueryTestResultsTestResultsQueryGetResponse = (PaginatedTestResults);

export type ReadTestResultTestResultsTestResultIdGetData = {
    testResultId: number;
};

export type ReadTestResultTestResultsTestResultIdGetResponse = (TestResultResponse);

export type GetUserUserGetResponse = (UserResponse);

export type ChangePasswordUserPasswordPutData = {
    requestBody: UserVerification;
};

export type ChangePasswordUserPasswordPutResponse = (void);

export type ChangeEmailUserEmailEmailPutData = {
    email: string;
};

export type ChangeEmailUserEmailEmailPutResponse = (void);