/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutCompareTestRunsRouteImport } from './routes/_layout/compare-test-runs'
import { Route as LayoutResourcesRouteImport } from './routes/_layout/resources'
import { Route as LayoutSearchRouteImport } from './routes/_layout/search'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutTestResultsRouteImport } from './routes/_layout/test-results'
import { Route as LayoutCompareTestRunsIndexRouteImport } from './routes/_layout/compare-test-runs.index'
import { Route as LayoutCompareTestRunsResultsRouteImport } from './routes/_layout/compare-test-runs.results'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCompareTestRunsRoute = LayoutCompareTestRunsRouteImport.update({
  id: '/compare-test-runs',
  path: '/compare-test-runs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResourcesRoute = LayoutResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSearchRoute = LayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTestResultsRoute = LayoutTestResultsRouteImport.update({
  id: '/test-results',
  path: '/test-results',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCompareTestRunsIndexRoute =
  LayoutCompareTestRunsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutCompareTestRunsRoute,
  } as any)
const LayoutCompareTestRunsResultsRoute =
  LayoutCompareTestRunsResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => LayoutCompareTestRunsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/compare-test-runs': typeof LayoutCompareTestRunsRouteWithChildren
  '/resources': typeof LayoutResourcesRoute
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/test-results': typeof LayoutTestResultsRoute
  '/compare-test-runs/results': typeof LayoutCompareTestRunsResultsRoute
  '/compare-test-runs/': typeof LayoutCompareTestRunsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/resources': typeof LayoutResourcesRoute
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/test-results': typeof LayoutTestResultsRoute
  '/': typeof LayoutIndexRoute
  '/compare-test-runs/results': typeof LayoutCompareTestRunsResultsRoute
  '/compare-test-runs': typeof LayoutCompareTestRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/compare-test-runs': typeof LayoutCompareTestRunsRouteWithChildren
  '/_layout/resources': typeof LayoutResourcesRoute
  '/_layout/search': typeof LayoutSearchRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/test-results': typeof LayoutTestResultsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/compare-test-runs/results': typeof LayoutCompareTestRunsResultsRoute
  '/_layout/compare-test-runs/': typeof LayoutCompareTestRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/compare-test-runs'
    | '/resources'
    | '/search'
    | '/settings'
    | '/test-results'
    | '/compare-test-runs/results'
    | '/compare-test-runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/admin'
    | '/resources'
    | '/search'
    | '/settings'
    | '/test-results'
    | '/'
    | '/compare-test-runs/results'
    | '/compare-test-runs'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/compare-test-runs'
    | '/_layout/resources'
    | '/_layout/search'
    | '/_layout/settings'
    | '/_layout/test-results'
    | '/_layout/'
    | '/_layout/compare-test-runs/results'
    | '/_layout/compare-test-runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/compare-test-runs': {
      id: '/_layout/compare-test-runs'
      path: '/compare-test-runs'
      fullPath: '/compare-test-runs'
      preLoaderRoute: typeof LayoutCompareTestRunsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/resources': {
      id: '/_layout/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof LayoutResourcesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/test-results': {
      id: '/_layout/test-results'
      path: '/test-results'
      fullPath: '/test-results'
      preLoaderRoute: typeof LayoutTestResultsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/compare-test-runs/': {
      id: '/_layout/compare-test-runs/'
      path: '/'
      fullPath: '/compare-test-runs/'
      preLoaderRoute: typeof LayoutCompareTestRunsIndexRouteImport
      parentRoute: typeof LayoutCompareTestRunsRoute
    }
    '/_layout/compare-test-runs/results': {
      id: '/_layout/compare-test-runs/results'
      path: '/results'
      fullPath: '/compare-test-runs/results'
      preLoaderRoute: typeof LayoutCompareTestRunsResultsRouteImport
      parentRoute: typeof LayoutCompareTestRunsRoute
    }
  }
}

interface LayoutCompareTestRunsRouteChildren {
  LayoutCompareTestRunsResultsRoute: typeof LayoutCompareTestRunsResultsRoute
  LayoutCompareTestRunsIndexRoute: typeof LayoutCompareTestRunsIndexRoute
}

const LayoutCompareTestRunsRouteChildren: LayoutCompareTestRunsRouteChildren = {
  LayoutCompareTestRunsResultsRoute: LayoutCompareTestRunsResultsRoute,
  LayoutCompareTestRunsIndexRoute: LayoutCompareTestRunsIndexRoute,
}

const LayoutCompareTestRunsRouteWithChildren =
  LayoutCompareTestRunsRoute._addFileChildren(
    LayoutCompareTestRunsRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutCompareTestRunsRoute: typeof LayoutCompareTestRunsRouteWithChildren
  LayoutResourcesRoute: typeof LayoutResourcesRoute
  LayoutSearchRoute: typeof LayoutSearchRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTestResultsRoute: typeof LayoutTestResultsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutCompareTestRunsRoute: LayoutCompareTestRunsRouteWithChildren,
  LayoutResourcesRoute: LayoutResourcesRoute,
  LayoutSearchRoute: LayoutSearchRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTestResultsRoute: LayoutTestResultsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
